version: '3.8'
services:
  ServiceA.api:
    image: service-a-image
    build:
      context: .
      dockerfile: Microservice1.API/Dockerfile
  ServiceB.api:
    image: service-b-image
    build:
      context: .
      dockerfile: Microservice2.API/Dockerfile
  Services-Discovery :
     image : steeltoeoss/eureka-server
     expose:
     - 8761
     ports:
     - 8761:8761
     

