version: '3.4'

services:
  ServiceA.api:
    ports:
      - "5010:80"
      - "5011:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
  ServiceB.api:
    ports:
      - "5020:80"
      - "5021:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

